version: '3.8'

services:
  web:
    build: .
    volumes: &web-volumes
      - &app-volume .:/budget_tracker:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    ports:
      - 4444:4444
      - 4445:4445
      - 4446:4446
    depends_on:
      - db
    environment: &web-environment
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 4444
      RUBYOPT: -W:no-deprecated -W:no-experimental
    command: bundle exec rails s -b '0.0.0.0' -p 4444

  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  bundle_cache:
